### PR TITLE
Remove latex sources

### PR DESCRIPTION
**Pull request by diehlpk**
We should remove the image and latex sources from the repo.

### CODE REVIEW

**Review by G-071 — COMMENTED** [review]
Is the content of the silo_format.tex already available on the new website? I just took a quick glance but could not see it.

**Comment by diehlpk** [comment]
That was never published with doxygen and might be there for a long time.

**Comment by G-071** [comment]
The information in there still appears to be relevant, though. I don't think we have changed the silo format in a long time.
I would at least keep this one file until we can get it into the documentation some other way.

**Comment by dmarce1** [comment]
I set up the branch old_docs, from the commit just before this one.

**Pull request merged**
