### PR TITLE
Distributed scaling

### PR DESCRIPTION
**Pull request by sithhell**
This PR is improving distributed scaling significantly. What's missing is is a verification if the physics are still correct. the CI tests won't validate anymore due to a change of output.

### CODE REVIEW

**Comment by dmarce1** [comment]
Thomas-

The moving_star test is not giving the correct result on your branch, but
neither is it on the master branch (even though it's getting validated).
The results are the same between the two branches. I'm not sure why the
validation is coming back as passed when the results are off. I will look
into what's going on.


-Dominic

**Comment by dmarce1** [comment]
Thomas-

I have fixed the bug on the master branch that was causing the issues. The
distributed_scaling run gives correct results now.


-Dominic

**Comment by hkaiser** [comment]
@sithhell could you please rebase this on master for @dmarce1 to be able to merge this?

**Comment by sithhell** [comment]
The branch is rebased, but seems to give a floating point exception at runtime right now ... should we continue to merge it onto master?

**Pull request merged**
