### PR TITLE
License

### PR DESCRIPTION
**Pull request by diehlpk**
Add the boost license to all hpp, cpp, and cmake files.

### CODE REVIEW

**Comment by sithhell** [comment]
I don't think these changes are correct, you removed authors from the copyright section and not all are attributed.

**Comment by dmarce1** [comment]
Regarding what Thomas is saying, I think he's right. I spoke with Hartmut yesterday he says the correct thing to do is leave all the author copyrights as is, just remove any licensing language and replace it with boost (though in fact none of the files that did have licenses had anything but boost anyway).

**Comment by diehlpk** [comment]
My intention was to add Dominic, since he was the founder. And people should add their names to the files they claim authorship. Many files did not have any authors, Dominic added his name to some but not all files. Gregor and I for example never added our names, Parsa did for some files and for some not.

**Comment by diehlpk** [comment]
> I don't think these changes are correct, you removed authors from the copyright section and not all are attributed.

@sithhell Who are all? All people contributed to the code? All people having a commit? Do I add this people to all files or only the file the committed to? Do you want go through the commit log and gather this information?

**Comment by diehlpk** [comment]
> I don't think these changes are correct, you removed authors from the copyright section and not all are attributed.

Yes, you are corrected for the first part and I added these authors.

**Comment by diehlpk** [comment]
> > I don't think these changes are correct, you removed authors from the copyright section and not all are attributed.
> 
> @sithhell Who are all? All people contributed to the code? All people having a commit? Do I add this people to all files or only the file the committed to? Do you want go through the commit log and gather this information?

Ok, using 

`git log --format='%an <%ae>' | sort -n | uniq -c`

results in following authors 

Andreas Schaefer
Bryce Adelstein-Lelbach aka wash 
David Pfander
Dominic Marcello 
Gregor Daiss 
Hartmut Kaiser 
John Biddiscombe 
Kevin Huck
Parsa Amini 
Patrick Diehl
Thomas Heller 

We might want to add these authors to all of the files, Doing this on a file basis by hand is too time consuming.

**Comment by diehlpk** [comment]
The current solutions is to have a AUTHORS file with all the names of the people contributed to the current version of the master branch. 

And to all cpp, hpp, and CMakeFiles.txt, I added` //  Copyright (c) 2019 AUTHORS`

**Pull request merged**
