### PR TITLE
cmake: fix cuda restriction for C++20

### PR DESCRIPTION
**Pull request by junghans**

### CODE REVIEW

**Comment by junghans** [comment]
@diehlpk

**Comment by diehlpk** [comment]
@junghans thanks. I will merge it once the tests passed.

**Comment by junghans** [comment]
@G-071 what is the build failure?

**Comment by G-071** [comment]
The build failures were unrelated. We simply needed to adapt our Jenkins pipelines to a few changes (see #474 ). 

The changes in this PR here seem simple enough -- though for completion’s sake I will wait with merging it until #474  is merged first, and the updated tests pass here as well.

**Review by G-071 — APPROVED** [review]

**Pull request merged**
