### PR TITLE
Combine set_omega with refinement

### PR DESCRIPTION
**Pull request by hkaiser**
@dmarce1 Please verify this does not break anything

### CODE REVIEW

**Comment by dmarce1** [comment]
Hartmut-

I get a seg fault while loading from restart.
I fixed a bug with omega on the main branch earlier today, this may be the
reason.

-Dominic


0x2b90af02c1e8  : hpx::termination_handler(int) + 0x158 in
/home/dmarce1/lib/libhpx.so.1
0x317f40f7e0    : ??? + 0x317f40f7e0 in /lib64/libpthread.so.0
0x2b90b05e3284  :
hpx::lcos::local::detail::condition_variable::abort_all(std::unique_lock<hpx::lcos::local::spinlock>)
+ 0x4 in /home/dmarce1/lib/libhpx.so.1
{what}: Segmentation fault

-Dominic

**Comment by hkaiser** [comment]
@dmarce1 How do I reproduce your issue?

**Comment by hkaiser** [comment]
@dmarce1 Also, circle-ci seems to be ok with this patch, doesn't that include doing a small run using a restart file?

**Comment by sithhell** [comment]
Is this good to go now? This is important for our scaling runs.

**Comment by dmarce1** [comment]
Thomas

Not yet. I need to verify the crash I saw earlier was related to a bug on
master. I will check it out later tonight.

Dominic

**Comment by dmarce1** [comment]
Hartmut-

Looks like it is working when I run it, but there is a bug I can spot in
the code.
grid::omega is a static, so the first line in "check_for_refinment" in
node_server_actions_2.cpp, "grid::omega = omega;", needs to be locked off
(or only happen once per locality)

-Dominic

**Comment by sithhell** [comment]
This is fixed now.  good to merge?

**Comment by hkaiser** [comment]
> grid::omega is a static, so the first line in "check_for_refinment" in node_server_actions_2.cpp, "grid::omega = omega;", needs to be locked off (or only happen once per locality)

I was assuming this to be a benign race. But yes, we should protect this from multi-threaded access.

**Pull request merged**
