### PR TITLE
Possible fix for form_tree bug

### PR DESCRIPTION
**Pull request by diehlpk**
It seems that the hanging in the from tree step got less with this bug.

### CODE REVIEW

**Comment by diehlpk** [comment]
@shibersag Can you please have a look?

**Comment by diehlpk** [comment]
@shibersag Can you please have a look?

**Comment by diehlpk** [comment]
@shibersag Can you please have a look?

**Review by G-071 — APPROVED** [review]
I'm still not convinced that this completely resolves the issue you were facing—however, all the tests pass and some local node-level tests showed no significant performance impact, so I don't really see any problem with merging this.

**Pull request merged**
